{% set name = "cmark-gfm" %}
{% set version = "0.29.0.gfm.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/github/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: cca50828244dfa7a6893d34ca3eb80bd4c7bd612f0645f5b57d5fd32e74f7077

build:
  number: 0
  run_exports:
    - {{ pin_subpackage("cmark-gfm") }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]

test:
  commands:
    - cmark-gfm --version
    - if not exist %LIBRARY_BIN%\cmark-gfm.dll exit 1              # [win]
    - test -f $PREFIX/lib/libcmark-gfm.so                          # [linux]
    - test -f $PREFIX/lib/libcmark-gfm.dylib                       # [osx]
    - if not exist %LIBRARY_BIN%\cmark-gfm-extensions.dll exit 1   # [win]
    - test -f $PREFIX/lib/libcmark-gfm-extensions.so               # [linux]
    - test -f $PREFIX/lib/libcmark-gfm-extensions.dylib            # [osx]
    - if not exist %LIBRARY_INC%\cmark-gfm-extension_api.h exit 1  # [win]
    - test -f $PREFIX/include/cmark-gfm-extension_api.h            # [unix]

about:
  home: https://github.com/github/cmark-gfm
  license: BSD-2-Clause
  license_family: BSD
  license_file: COPYING
  summary: GitHub's Fork of cmark
  description: |
    cmark-gfm is an extended version of the C reference implementation of
    CommonMark, a rationalized version of Markdown syntax with a spec.
    cmark-gfm adds GitHub Flavored Markdown extensions to the upstream
    implementation.
  dev_url: https://github.com/github/cmark-gfm
  doc_url: https://github.github.com/gfm/

extra:
  recipe-maintainers:
    - saraedum
